polling project/accounts/urls.py
from django.urls import path
from . import views
app_name = "accounts"
urlpatterns=[
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.create_user, name='register'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('about-us/', views.about_us, name='about_us'),
    path('our-services/', views.our_services, name='our_services'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('contact/', views.contact, name='contact'),
]

polling project/pollme/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name='home'),
    path('polls/', include('polls.urls', namespace="polls")),
    path('accounts/', include('accounts.urls', namespace="accounts")),

]

polling project/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path('list/', views.polls_list, name='list'),
    path('list/user/', views.list_by_user, name='list_by_user'),
    path('add/', views.polls_add, name='add'),
    path('edit/<int:poll_id>/', views.polls_edit, name='edit'),
    path('delete/<int:poll_id>/', views.polls_delete, name='delete_poll'),
    path('end/<int:poll_id>/', views.endpoll, name='end_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:choice_id>/',
         views.choice_delete, name='choice_delete'),
    path('<int:poll_id>/', views.poll_detail, name='detail'),
    path('<int:poll_id>/vote/', views.poll_vote, name='vote'),
]

polling project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Online Web Polling</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
        crossorigin="anonymous">
    {% block custom_css %}{% endblock custom_css %}
</head>
<body>
    {% include 'includes/navbar.html' %}
    {% block content %}
    {% endblock content %}
    <!-- javascript files -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>

polling project/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block custom_css %}
<link rel="stylesheet" href="{% static 'css/home_style.css' %}">
{% endblock custom_css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div id="home-content">
                <h1>Poll with Us !</h1>
                <h3>Your voice can be heard through your votes!</h3>
                <hr>
                <a class="btn btn-light btn-lg" href="{% url 'polls:list' %}" role="button">Lets make a change!</a>
            </div>
        </div>
    </div>
</div>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="footer-container">
    <!-- Column 1 for Static Links -->
    <div class="footer-column">
           <h5>Company</h5>
        <a href="{% url 'accounts:about_us' %}">About Us</a>
        <a href="{% url 'accounts:our_services' %}">Our Services</a>
    </div>
    <!-- Column 2 for Static Links -->
    <div class="footer-column">
        <h5>Get to Know us!</h5>
        <a href="{% url 'accounts:privacy_policy' %}">Privacy & Policy</a>
        <a href="{% url 'accounts:contact' %}">Get in Touch</a>
    </div>
    <!-- Column 3 for Quick Links -->
    <div class="footer-column quick-links">
        <h5>Quick Action</h5>
        <ul>
            <li><a href="{% url 'accounts:register' %}">Registration</a></li>
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
        </ul>
    </div>
    <!-- Newsletter Form -->
    <div class="footer-column newsletter">
        {% include "accounts/_subscribe_form.html" %}
    </div>
</div>
{% endblock content %}