polling project/accounts/urls.py
from django.urls import path
from . import views
app_name = "accounts"
urlpatterns=[
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.create_user, name='register'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('about-us/', views.about_us, name='about_us'),
    path('our-services/', views.our_services, name='our_services'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('contact/', views.contact, name='contact'),
]

polling project/pollme/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name='home'),
    path('polls/', include('polls.urls', namespace="polls")),
    path('accounts/', include('accounts.urls', namespace="accounts")),

]

polling project/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path('list/', views.polls_list, name='list'),
    path('list/user/', views.list_by_user, name='list_by_user'),
    path('add/', views.polls_add, name='add'),
    path('edit/<int:poll_id>/', views.polls_edit, name='edit'),
    path('delete/<int:poll_id>/', views.polls_delete, name='delete_poll'),
    path('end/<int:poll_id>/', views.endpoll, name='end_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:choice_id>/',
         views.choice_delete, name='choice_delete'),
    path('<int:poll_id>/', views.poll_detail, name='detail'),
    path('<int:poll_id>/vote/', views.poll_vote, name='vote'),
]

polling project/accounts/models.py
from django.db import models
class NewsletterSubscription(models.Model):
    email = models.EmailField(unique=True)
    date_subscribed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

polling project/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
class UserRegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100, min_length=5,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email', max_length=20, min_length=5,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Password', max_length=50, min_length=5,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password',
                                max_length=50, min_length=5,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

polling project/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import UserRegistrationForm
from django.contrib import messages
from .models import NewsletterSubscription
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            redirect_url = request.GET.get('next', 'home')
            return redirect(redirect_url)
        else:
            messages.error(request, "Username Or Password is incorrect!!",
                           extra_tags='alert alert-warning alert-dismissible fade show')

    return render(request, 'accounts/login.html')
def logout_user(request):
    logout(request)
    return redirect('home')
def create_user(request):
    if request.method == 'POST':
        check1 = False
        check2 = False
        check3 = False
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            email = form.cleaned_data['email']
            if password1 != password2:
                check1 = True
                messages.error(request, 'Password doesn\'t matched',
                               extra_tags='alert alert-warning alert-dismissible fade show')
            if User.objects.filter(username=username).exists():
                check2 = True
                messages.error(request, 'Username already exists',
                               extra_tags='alert alert-warning alert-dismissible fade show')
            if User.objects.filter(email=email).exists():
                check3 = True
                messages.error(request, 'Email already registered',
                               extra_tags='alert alert-warning alert-dismissible fade show')

            if check1 or check2 or check3:
                messages.error(
                    request, "Registration Failed", extra_tags='alert alert-warning alert-dismissible fade show')
                return redirect('accounts:register')
            else:
                user = User.objects.create_user(
                    username=username, password=password1, email=email)
                messages.success(
                    request, f'Thanks for registering {user.username}!', extra_tags='alert alert-success alert-dismissible fade show')
                return redirect('accounts:login')
    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'form': form})

def subscribe(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        # Checking if the email already exists in the database:
        if not NewsletterSubscription.objects.filter(email=email).exists():
         NewsletterSubscription.objects.create(email=email)
         messages.success(request, 'Subscribed successfully!')
    else:
        messages.warning(request, 'This email is already subscribed.')
        pass
        return redirect('home')  # Redirect back to the home page.

    return render(request, 'home.html')
def home(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        # Checking if the email already exists?
        if not NewsletterSubscription.objects.filter(email=email).exists():
            NewsletterSubscription.objects.create(email=email)
            messages.success(request, 'Subscribed!')
        else:
             messages.warning(request, 'Email is already subscribed.')
        return redirect('home')
    return render(request, 'home.html')
#homepage html connect links.
def about_us(request):
    return render(request, 'static_pages/about_us.html')
def our_services(request):
    return render(request, 'static_pages/our_services.html')
def privacy_policy(request):
    return render(request, 'static_pages/privacy_policy.html')
def contact(request):
    return render(request, 'accounts/contact.html')

polling project/accounts/templates/accounts/_subscribe_form.html
<div style="margin: 50px; padding: 20px; border: 1px solid #ddd; border-radius: 5px; width: 300px;">
    <h2>Newsletter</h2>
    <p>Sign up with us!</p>
    <form method="post" action="{% url 'accounts:subscribe' %}">
        {% csrf_token %}
        <label>
            <input type="email" name="email" placeholder="Your email" style="width: 100%; padding: 10px; margin-bottom: 10px;">
        </label>
        <button type="submit" style="width: 100%; padding: 10px; background-color: #007BFF; color: white; border: none; border-radius: 5px;">SignUp</button>
    </form>
</div>

polling project/accounts/templates/accounts/contact.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> Contact Us </title>
    <link rel="stylesheet" href="/static/css/contact.css"/>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
    <div class="content">
      <div class="left-side">
        <div class="address details">
          <!--<i class="fas fa-map-marker-alt"></i>-->
          <div class="topic">Address</div>
          <div class="text-one">Atur Centre, Symbiosis Institute of Computer Research & Studies</div>
          <div class="text-two">Model Colony, Pune- 411016</div>
        </div>
        <div class="phone details">
          <!--<i class="fas fa-phone-alt"></i>-->
          <div class="topic">Phone</div>
          <div class="text-one">+91 9582943564</div>
        </div>
        <div class="email details">
          <!---<i class="fas fa-envelope"></i>-->
          <div class="topic">Email</div>
          <div class="text-one">kminocha@gmail.com</div>
        </div>
      </div>
      <div class="right-side">
        <div class="topic-text">Send us a message</div>
        <p>If you have any types of quries related to our museum, you can send us message from here.
           It will be our pleasure to help & assit you. Click Here to Donate.</p>
      <form action="#">
        <div class="input-box">
          <input type="text" placeholder="Enter your name">
        </div>
        <div class="input-box">
          <input type="text" placeholder="Enter your email">
        </div>
        <div class="input-box message-box">
          <textarea placeholder="Enter your message"></textarea>
        </div>
        <div class="button">
          <input type="button" value="Send" >
        </div>
      </form>
    </div>
    </div>
  </div>

</body>
</html>

polling project/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" name="username" placeholder="Enter Username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
                <p>Wanna Join us? <a href="{% url 'accounts:register' %}">Register Here</a></p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

polling project/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <p>Already have an account? <a href="{% url 'accounts:login' %}">Login Here</a></p>
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}